/* Generated By:JavaCC: Do not edit this line. AseCCParserConstants.java */
package cnc.parser.ase;

public interface AseCCParserConstants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;
  int ASTERISK = 7;
  int DIGIT = 8;
  int NUMBER = 9;
  int MESH_VERTEX = 10;
  int MESH_FACE_LIST = 11;
  int MESH_FACE = 12;
  int DSMAX_ASCIIEXPORT = 13;
  int MESH_VERTEX_LIST = 14;
  int PROP_RECVSHADOW = 15;
  int MESH_SMOOTHING = 16;
  int MESH_MTLID = 17;
  int ID = 18;
  int SERVSYMB = 19;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"*\"",
    "<DIGIT>",
    "<NUMBER>",
    "\"MESH_VERTEX\"",
    "\"MESH_FACE_LIST\"",
    "\"MESH_FACE\"",
    "\"DSMAX_ASCIIEXPORT\"",
    "\"MESH_VERTEX_LIST\"",
    "\"PROP_RECVSHADOW\"",
    "\"MESH_SMOOTHING\"",
    "\"MESH_MTLID\"",
    "<ID>",
    "<SERVSYMB>",
  };

}
